### ISSUE TITLE
Questions about the Implementation of Graph Convolution

### ISSUE THREAD

**Issue by plaxkk** [VeritasYin/STGCN_IJCAI-18#11]
In code,the function Conv_Graph（）, I can't understand the computing process.

can you explaine it in detail，why tanspose,why reshape？

BTW，in the paper, you say Ci=1，but in code it seems to be 32？

or，can you introduce some material for study to help me understand the process？

**Comment by VeritasYin** [comment]
1) Try to calculate the dimension of tensor variables in each process that would help you understand the code and explain the reason of operations in transposing and reshaping.

2) Please notice that the initial input channel 'C0' is 1. After that, 'Ci' will change for each layer.

3) As for study materials, please read the reference list of our paper.

Thank you once again for your interest in our program. We have already publicly released the paper at arXiv and the code at GitHub. Due to time limitation, we probably couldn't offer timely response to each question. Though, you're free to raise an issue if you find some potential problems in the code.

Good luck, ht

**Comment by plaxkk** [comment]
what confused me most is there is a sum operation  in formulation 3 of the paper，but it is not reflected in code

**Comment by VeritasYin** [comment]
Please refer to the Code: line 33, function 'Cheb_Poly(L, Ks, n)' and line 265 for the details.

I'm afraid that you may not fully read the code and understand the paper. I suggest you that you may need to take some time to read and review it over again. Util then, you may raise an issue to ask the remaining doubts.

**Comment by plaxkk** [comment]
thx a lot，I have read the code and the paper for two weeks.may be I have to take more time on gcn and the computation of the formulation.

btw，thank for your patience.
