### ISSUE TITLE
Solving for 2 variables

### ISSUE THREAD

**Issue by ahariri13** [VeritasYin/STGCN_IJCAI-18#28]
What are the main modifications for me to consider if I were to solve for more than just velocity ?  I believe the number of channels should be changed accordingly ? (2 variables to be predicted meaning 2 channels).

On the other hand, could you please elaborate on what was done in the lines below ? It wasn't very clear to me how they contributed to the multi-prediction function 

step_idx = tmp_idx = np.arange(3, n_pred + 1, 3) - 1
            min_val = min_va_val = np.array([4e1, 1e5, 1e5] * len(step_idx))

**Comment by VeritasYin** [comment]
Yes, if you want to predict the variable with multiple dimensions, you should modify the size of input channel 'C_in'. Also, you might need to tune the channel size inner the ST-Conv blocks.

As for the code below, since we predict the final step through multiple iterations. So, for each training step, we predict all 9 time-steps and just keep the 3rd, 6th and 9th value for the baseline comparison. 'step_idx' is indices of those variables. The last line is initialized metrics.
